# config/application.yml
#theme = %w(amelia cerulean cyborg journal readable simplex slate spacelab spruce superhero united)
defaults: &defaults
  app_name: "BBTangCMS"
  cool:
    saweet: nested settings
  neat_setting: 24
  theme: 'readable'
  today_theme: ''
  theme1: 'united'
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
