# config/application.yml
#theme = %w(amelia cerulean cyborg journal readable simplex slate spacelab spruce superhero united)
defaults: &defaults
  app_name: "BBTangCMS"
  cool:
    saweet: nested settings
  neat_setting: 24
  theme: 'readable'
  version_mod: "Knowledge Question Answer News Subject Profile CategoryBase"
  worked_mod: "Knowledge Question Answer News Subject Profile CategoryBase"
  today_theme: ''
  theme1: 'united'
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>
  observe_models: Knowledge Note News Profile Question Quiz  QuizCollection Subject User Attachment CmsRole
development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
