# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 55

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 55

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 55

group_development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: group_development
  pool: 55
  host: localhost
  username: bbtang
  password: bbtang

group_production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: group_production
  pool: 55
  host: localhost
  username: bbtang
  password: bbtang

group_test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: group_test
  pool: 55
  host: localhost
  username: bbtang
  password: bbtang


bbtcms_development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bbtcms_development
  pool: 55
  host: localhost
  username: bbtang
  password: bbtang

bbtcms_production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bbtcms_production
  pool: 55
  host: localhost
  username: bbtang
  password: bbtang

bbtcms_test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bbtcms_test
  pool: 55
  host: localhost
  username: bbtang
  password: bbtang

ecshop:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ecshop
  pool: 55
  host: localhost
  username: yangming
  password: SKtMYSNESMGeArcM
