defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: bbtang_development

test:
  <<: *defaults
  database: bbtang_test

production:
  <<: *defaults
  database: bbtang_development
