permit:
  create_profile: create_profile
  create_knowledge: create_knowledge
  #create_category_base: create_category_base
  create_attachment: create_attachment
  create_question: create_question
  create_question_answer: create_question_answer
  create_tag_identity: create_tag_identity
  create_tag_identities_timeline: create_tag_identities_timeline
  create_tag_identities_timelines_category: create_tag_identities_timelines_category
  #create_recommend_recommend_event: create_recommend_recommend_event
  #create_recommend_recommend_mtool: create_recommend_recommend_mtool
  create_recommend_recommend_app: create_recommend_recommend_app
  create_recommend_recommend_other: create_recommend_recommend_other
  create_recommend_other_column: create_recommend_other_column
  create_recommend_expert_category: create_recommend_expert_category
  create_recommend_vip_category: create_recommend_vip_category
  create_recommend_recommend_product: create_recommend_recommend_product
  create_recommend_recommend_question: create_recommend_recommend_question
  create_recommend_recommend_quiz: create_recommend_recommend_quiz
  create_recommend_recommend_subject: create_recommend_recommend_subject
  create_recommend_recommend_tag: create_recommend_recommend_tag
  create_recommend_recommend_user: create_recommend_recommend_user
  create_recommend_recommend_hindex: create_recommend_recommend_hindex
  create_recommend_recommend_ptag: create_recommend_recommend_ptag
  create_work_contact: create_work_contact
  create_quiz_center_quiz: create_quiz_center_quiz
  create_quiz_center_quiz_collection: create_quiz_center_quiz_collection
  update_profile: update_profile
  update_knowledge: update_knowledge
  #update_category_base: update_category_base
  update_attachment: update_attachment
  update_question: update_question
  update_note: update_note
  update_question_answer: update_question_answer
  #update_tag_identity: update_tag_identity
  #update_tag_identities_timeline: update_tag_identities_timeline
  update_tag_identities_timelines_category: create_tag_identities_timelines_category
  update_recommend_expert_category: update_recommend_expert_category
  update_recommend_vip_category: update_recommend_vip_category
  update_recommend_recommend_app: update_recommend_recommend_app
  update_recommend_recommend_other: update_recommend_recommend_other
  update_recommend_other_column: update_recommend_other_column
  update_recommend_recommend_product: update_recommend_recommend_product
  update_recommend_recommend_question: update_recommend_recommend_question
  update_recommend_recommend_quiz: update_recommend_recommend_quiz
  update_recommend_recommend_subject: update_recommend_recommend_subject
  update_recommend_recommend_tag: update_recommend_recommend_tag
  update_recommend_recommend_user: update_recommend_recommend_user
  update_recommend_recommend_hindex: update_recommend_recommend_hindex
  update_recommend_recommend_ptag: update_recommend_recommend_ptag
  update_quiz_center_quiz: update_quiz_center_quiz
  update_quiz_center_quiz_collection: update_quiz_center_quiz_collection
  update_work_contact: update_work_contact
  read_profile: read_profile
  read_knowledge: read_knowledge
  #read_category_base: read_category_base
  read_attachment: read_attachment
  read_question: read_question
  read_note: read_note
  read_question_answer: read_question_answer
  read_tag_identity: read_tag_identity
  read_tag_identities_timeline: read_tag_identities_timeline
  read_tag_identities_timelines_category: read_tag_identities_timelines_category
  read_recommend_expert_category: read_recommend_expert_category
  read_recommend_vip_category: read_recommend_vip_category
  read_recommend_recommend_app: read_recommend_recommend_app
  read_recommend_recommend_other: read_recommend_recommend_other
  read_recommend_other_column: read_recommend_other_column
  read_recommend_recommend_product: read_recommend_recommend_product
  read_recommend_recommend_question: read_recommend_recommend_question
  read_recommend_recommend_quiz: read_recommend_recommend_quiz
  read_recommend_recommend_subject: read_recommend_recommend_subject
  read_recommend_recommend_tag: read_recommend_recommend_tag
  read_recommend_recommend_user: read_recommend_recommend_user
  read_recommend_recommend_hindex: read_recommend_recommend_hindex
  read_recommend_recommend_ptag: read_recommend_recommend_ptag
  read_quiz_center_quiz: read_quiz_center_quiz
  read_quiz_center_quiz_collection: read_quiz_center_quiz_collection
  read_work_contact: read_work_contact
  destroy_profile: destroy_profile
  destroy_knowledge: destroy_knowledge
  #destroy_category_base: destroy_category_base
  destroy_attachment: destroy_attachment
  destroy_question: destroy_question
  destroy_note: destroy_note
  destroy_question_answer: destroy_question_answer
  #destroy_tag_identity: destroy_tag_identity
  #destroy_tag_identities_timeline: destroy_tag_identities_timeline
  destroy_tag_identities_timelines_category: destroy_tag_identities_timelines_category
  destroy_recommend_expert_category: destroy_recommend_expert_category
  destroy_recommend_vip_category: destroy_recommend_vip_category
  destroy_recommend_recommend_app: destroy_recommend_recommend_app
  destroy_recommend_recommend_other: destroy_recommend_recommend_other
  destroy_recommend_other_column: destroy_recommend_other_column
  destroy_recommend_recommend_product: destroy_recommend_recommend_product
  destroy_recommend_recommend_question: destroy_recommend_recommend_question
  destroy_recommend_recommend_quiz: destroy_recommend_recommend_quiz
  destroy_recommend_recommend_subject: destroy_recommend_recommend_subject
  destroy_recommend_recommend_tag: destroy_recommend_recommend_tag
  destroy_recommend_recommend_user: destroy_recommend_recommend_user
  destroy_recommend_recommend_hindex: destroy_recommend_recommend_hindex
  destroy_recommend_recommend_ptag: destroy_recommend_recommend_ptag
  destroy_quiz_center_quiz: destroy_quiz_center_quiz
  destroy_quiz_center_quiz_collection: destroy_quiz_center_quiz_collection
  destroy_work_contact: destroy_work_contact
  resetscore_question: resetscore_question
