development:
  bin_path: /usr/local/coreseek/bin
  charset_type: zh_cn.utf-8
  charset_dictpath: /usr/local/mmseg3/etc
  config_file: config/development.sphinx.conf
  searchd_file_path: config/../../common/sphinx
  pid_file: config/../../common/sphinx/searchd.development.pid
  
production:
  bin_path: /usr/local/coreseek/bin
  charset_type: zh_cn.utf-8
  charset_dictpath: /usr/local/mmseg3/etc
  config_file: config/development.sphinx.conf
  searchd_file_path: config/../../common/sphinx
  pid_file: config/../../common/sphinx/searchd.production.pid
