require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Recommend::ExpertCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # Recommend::ExpertCategory. As you add validations to Recommend::ExpertCategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Recommend::ExpertCategoriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all recommend_expert_categories as @recommend_expert_categories" do
      expert_category = Recommend::ExpertCategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:recommend_expert_categories).should eq([expert_category])
    end
  end

  describe "GET show" do
    it "assigns the requested recommend_expert_category as @recommend_expert_category" do
      expert_category = Recommend::ExpertCategory.create! valid_attributes
      get :show, {:id => expert_category.to_param}, valid_session
      assigns(:recommend_expert_category).should eq(expert_category)
    end
  end

  describe "GET new" do
    it "assigns a new recommend_expert_category as @recommend_expert_category" do
      get :new, {}, valid_session
      assigns(:recommend_expert_category).should be_a_new(Recommend::ExpertCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested recommend_expert_category as @recommend_expert_category" do
      expert_category = Recommend::ExpertCategory.create! valid_attributes
      get :edit, {:id => expert_category.to_param}, valid_session
      assigns(:recommend_expert_category).should eq(expert_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Recommend::ExpertCategory" do
        expect {
          post :create, {:recommend_expert_category => valid_attributes}, valid_session
        }.to change(Recommend::ExpertCategory, :count).by(1)
      end

      it "assigns a newly created recommend_expert_category as @recommend_expert_category" do
        post :create, {:recommend_expert_category => valid_attributes}, valid_session
        assigns(:recommend_expert_category).should be_a(Recommend::ExpertCategory)
        assigns(:recommend_expert_category).should be_persisted
      end

      it "redirects to the created recommend_expert_category" do
        post :create, {:recommend_expert_category => valid_attributes}, valid_session
        response.should redirect_to(Recommend::ExpertCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recommend_expert_category as @recommend_expert_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        Recommend::ExpertCategory.any_instance.stub(:save).and_return(false)
        post :create, {:recommend_expert_category => {}}, valid_session
        assigns(:recommend_expert_category).should be_a_new(Recommend::ExpertCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Recommend::ExpertCategory.any_instance.stub(:save).and_return(false)
        post :create, {:recommend_expert_category => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recommend_expert_category" do
        expert_category = Recommend::ExpertCategory.create! valid_attributes
        # Assuming there are no other recommend_expert_categories in the database, this
        # specifies that the Recommend::ExpertCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Recommend::ExpertCategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => expert_category.to_param, :recommend_expert_category => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested recommend_expert_category as @recommend_expert_category" do
        expert_category = Recommend::ExpertCategory.create! valid_attributes
        put :update, {:id => expert_category.to_param, :recommend_expert_category => valid_attributes}, valid_session
        assigns(:recommend_expert_category).should eq(expert_category)
      end

      it "redirects to the recommend_expert_category" do
        expert_category = Recommend::ExpertCategory.create! valid_attributes
        put :update, {:id => expert_category.to_param, :recommend_expert_category => valid_attributes}, valid_session
        response.should redirect_to(expert_category)
      end
    end

    describe "with invalid params" do
      it "assigns the recommend_expert_category as @recommend_expert_category" do
        expert_category = Recommend::ExpertCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Recommend::ExpertCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => expert_category.to_param, :recommend_expert_category => {}}, valid_session
        assigns(:recommend_expert_category).should eq(expert_category)
      end

      it "re-renders the 'edit' template" do
        expert_category = Recommend::ExpertCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Recommend::ExpertCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => expert_category.to_param, :recommend_expert_category => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recommend_expert_category" do
      expert_category = Recommend::ExpertCategory.create! valid_attributes
      expect {
        delete :destroy, {:id => expert_category.to_param}, valid_session
      }.to change(Recommend::ExpertCategory, :count).by(-1)
    end

    it "redirects to the recommend_expert_categories list" do
      expert_category = Recommend::ExpertCategory.create! valid_attributes
      delete :destroy, {:id => expert_category.to_param}, valid_session
      response.should redirect_to(recommend_expert_categories_url)
    end
  end

end
