require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Recommend::RecommendQuizzesController do

  # This should return the minimal set of attributes required to create a valid
  # Recommend::RecommendQuiz. As you add validations to Recommend::RecommendQuiz, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Recommend::RecommendQuizzesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all recommend_recommend_quizzes as @recommend_recommend_quizzes" do
      recommend_quiz = Recommend::RecommendQuiz.create! valid_attributes
      get :index, {}, valid_session
      assigns(:recommend_recommend_quizzes).should eq([recommend_quiz])
    end
  end

  describe "GET show" do
    it "assigns the requested recommend_recommend_quiz as @recommend_recommend_quiz" do
      recommend_quiz = Recommend::RecommendQuiz.create! valid_attributes
      get :show, {:id => recommend_quiz.to_param}, valid_session
      assigns(:recommend_recommend_quiz).should eq(recommend_quiz)
    end
  end

  describe "GET new" do
    it "assigns a new recommend_recommend_quiz as @recommend_recommend_quiz" do
      get :new, {}, valid_session
      assigns(:recommend_recommend_quiz).should be_a_new(Recommend::RecommendQuiz)
    end
  end

  describe "GET edit" do
    it "assigns the requested recommend_recommend_quiz as @recommend_recommend_quiz" do
      recommend_quiz = Recommend::RecommendQuiz.create! valid_attributes
      get :edit, {:id => recommend_quiz.to_param}, valid_session
      assigns(:recommend_recommend_quiz).should eq(recommend_quiz)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Recommend::RecommendQuiz" do
        expect {
          post :create, {:recommend_recommend_quiz => valid_attributes}, valid_session
        }.to change(Recommend::RecommendQuiz, :count).by(1)
      end

      it "assigns a newly created recommend_recommend_quiz as @recommend_recommend_quiz" do
        post :create, {:recommend_recommend_quiz => valid_attributes}, valid_session
        assigns(:recommend_recommend_quiz).should be_a(Recommend::RecommendQuiz)
        assigns(:recommend_recommend_quiz).should be_persisted
      end

      it "redirects to the created recommend_recommend_quiz" do
        post :create, {:recommend_recommend_quiz => valid_attributes}, valid_session
        response.should redirect_to(Recommend::RecommendQuiz.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recommend_recommend_quiz as @recommend_recommend_quiz" do
        # Trigger the behavior that occurs when invalid params are submitted
        Recommend::RecommendQuiz.any_instance.stub(:save).and_return(false)
        post :create, {:recommend_recommend_quiz => {}}, valid_session
        assigns(:recommend_recommend_quiz).should be_a_new(Recommend::RecommendQuiz)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Recommend::RecommendQuiz.any_instance.stub(:save).and_return(false)
        post :create, {:recommend_recommend_quiz => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recommend_recommend_quiz" do
        recommend_quiz = Recommend::RecommendQuiz.create! valid_attributes
        # Assuming there are no other recommend_recommend_quizzes in the database, this
        # specifies that the Recommend::RecommendQuiz created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Recommend::RecommendQuiz.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => recommend_quiz.to_param, :recommend_recommend_quiz => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested recommend_recommend_quiz as @recommend_recommend_quiz" do
        recommend_quiz = Recommend::RecommendQuiz.create! valid_attributes
        put :update, {:id => recommend_quiz.to_param, :recommend_recommend_quiz => valid_attributes}, valid_session
        assigns(:recommend_recommend_quiz).should eq(recommend_quiz)
      end

      it "redirects to the recommend_recommend_quiz" do
        recommend_quiz = Recommend::RecommendQuiz.create! valid_attributes
        put :update, {:id => recommend_quiz.to_param, :recommend_recommend_quiz => valid_attributes}, valid_session
        response.should redirect_to(recommend_quiz)
      end
    end

    describe "with invalid params" do
      it "assigns the recommend_recommend_quiz as @recommend_recommend_quiz" do
        recommend_quiz = Recommend::RecommendQuiz.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Recommend::RecommendQuiz.any_instance.stub(:save).and_return(false)
        put :update, {:id => recommend_quiz.to_param, :recommend_recommend_quiz => {}}, valid_session
        assigns(:recommend_recommend_quiz).should eq(recommend_quiz)
      end

      it "re-renders the 'edit' template" do
        recommend_quiz = Recommend::RecommendQuiz.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Recommend::RecommendQuiz.any_instance.stub(:save).and_return(false)
        put :update, {:id => recommend_quiz.to_param, :recommend_recommend_quiz => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recommend_recommend_quiz" do
      recommend_quiz = Recommend::RecommendQuiz.create! valid_attributes
      expect {
        delete :destroy, {:id => recommend_quiz.to_param}, valid_session
      }.to change(Recommend::RecommendQuiz, :count).by(-1)
    end

    it "redirects to the recommend_recommend_quizzes list" do
      recommend_quiz = Recommend::RecommendQuiz.create! valid_attributes
      delete :destroy, {:id => recommend_quiz.to_param}, valid_session
      response.should redirect_to(recommend_recommend_quizzes_url)
    end
  end

end
