require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuizCenter::QuizCollectionsController do

  # This should return the minimal set of attributes required to create a valid
  # QuizCenter::QuizCollection. As you add validations to QuizCenter::QuizCollection, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuizCenter::QuizCollectionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all quiz_center_quiz_collections as @quiz_center_quiz_collections" do
      quiz_collection = QuizCenter::QuizCollection.create! valid_attributes
      get :index, {}, valid_session
      assigns(:quiz_center_quiz_collections).should eq([quiz_collection])
    end
  end

  describe "GET show" do
    it "assigns the requested quiz_center_quiz_collection as @quiz_center_quiz_collection" do
      quiz_collection = QuizCenter::QuizCollection.create! valid_attributes
      get :show, {:id => quiz_collection.to_param}, valid_session
      assigns(:quiz_center_quiz_collection).should eq(quiz_collection)
    end
  end

  describe "GET new" do
    it "assigns a new quiz_center_quiz_collection as @quiz_center_quiz_collection" do
      get :new, {}, valid_session
      assigns(:quiz_center_quiz_collection).should be_a_new(QuizCenter::QuizCollection)
    end
  end

  describe "GET edit" do
    it "assigns the requested quiz_center_quiz_collection as @quiz_center_quiz_collection" do
      quiz_collection = QuizCenter::QuizCollection.create! valid_attributes
      get :edit, {:id => quiz_collection.to_param}, valid_session
      assigns(:quiz_center_quiz_collection).should eq(quiz_collection)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new QuizCenter::QuizCollection" do
        expect {
          post :create, {:quiz_center_quiz_collection => valid_attributes}, valid_session
        }.to change(QuizCenter::QuizCollection, :count).by(1)
      end

      it "assigns a newly created quiz_center_quiz_collection as @quiz_center_quiz_collection" do
        post :create, {:quiz_center_quiz_collection => valid_attributes}, valid_session
        assigns(:quiz_center_quiz_collection).should be_a(QuizCenter::QuizCollection)
        assigns(:quiz_center_quiz_collection).should be_persisted
      end

      it "redirects to the created quiz_center_quiz_collection" do
        post :create, {:quiz_center_quiz_collection => valid_attributes}, valid_session
        response.should redirect_to(QuizCenter::QuizCollection.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved quiz_center_quiz_collection as @quiz_center_quiz_collection" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuizCenter::QuizCollection.any_instance.stub(:save).and_return(false)
        post :create, {:quiz_center_quiz_collection => {}}, valid_session
        assigns(:quiz_center_quiz_collection).should be_a_new(QuizCenter::QuizCollection)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuizCenter::QuizCollection.any_instance.stub(:save).and_return(false)
        post :create, {:quiz_center_quiz_collection => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested quiz_center_quiz_collection" do
        quiz_collection = QuizCenter::QuizCollection.create! valid_attributes
        # Assuming there are no other quiz_center_quiz_collections in the database, this
        # specifies that the QuizCenter::QuizCollection created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        QuizCenter::QuizCollection.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => quiz_collection.to_param, :quiz_center_quiz_collection => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested quiz_center_quiz_collection as @quiz_center_quiz_collection" do
        quiz_collection = QuizCenter::QuizCollection.create! valid_attributes
        put :update, {:id => quiz_collection.to_param, :quiz_center_quiz_collection => valid_attributes}, valid_session
        assigns(:quiz_center_quiz_collection).should eq(quiz_collection)
      end

      it "redirects to the quiz_center_quiz_collection" do
        quiz_collection = QuizCenter::QuizCollection.create! valid_attributes
        put :update, {:id => quiz_collection.to_param, :quiz_center_quiz_collection => valid_attributes}, valid_session
        response.should redirect_to(quiz_collection)
      end
    end

    describe "with invalid params" do
      it "assigns the quiz_center_quiz_collection as @quiz_center_quiz_collection" do
        quiz_collection = QuizCenter::QuizCollection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuizCenter::QuizCollection.any_instance.stub(:save).and_return(false)
        put :update, {:id => quiz_collection.to_param, :quiz_center_quiz_collection => {}}, valid_session
        assigns(:quiz_center_quiz_collection).should eq(quiz_collection)
      end

      it "re-renders the 'edit' template" do
        quiz_collection = QuizCenter::QuizCollection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuizCenter::QuizCollection.any_instance.stub(:save).and_return(false)
        put :update, {:id => quiz_collection.to_param, :quiz_center_quiz_collection => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested quiz_center_quiz_collection" do
      quiz_collection = QuizCenter::QuizCollection.create! valid_attributes
      expect {
        delete :destroy, {:id => quiz_collection.to_param}, valid_session
      }.to change(QuizCenter::QuizCollection, :count).by(-1)
    end

    it "redirects to the quiz_center_quiz_collections list" do
      quiz_collection = QuizCenter::QuizCollection.create! valid_attributes
      delete :destroy, {:id => quiz_collection.to_param}, valid_session
      response.should redirect_to(quiz_center_quiz_collections_url)
    end
  end

end
